In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
# Quickies
list = [0,1,4,3]
list_np = np.array(list) # converting list to array
list_step_size = np.arange(0,11,3) # arranged in order

# one dimensional vector of zeros
np.zeros(3)

# tuple of dimension 3x3
np.zeros((3,3))

#one dimensional vector of 10 evenly spaced points from 0 to 5. Uniform dist.
np.linspace(0,5,10)

#identitiy matrix 4x4
np.eye(4)

# reshape
arr = np.random.randint(1,50,25)
arr.reshape(5,5)

# max and min
arr.max()
arr.argmax() #index
arr.min()
arr.argmin() #index

# data type
arr.dtype

# boolean values as output
bool_arr = arr > 5 # values in arr greater than 5 will return True
arr[bool_arr] # will output values in arr greater than 5
OR arr[arr>5]


SyntaxError: invalid syntax (<ipython-input-2-8066166ce19c>, line 34)

In [ ]:
# Random numbers distributed from 0 to 1

np.random.rand(5) # one dimension
np.random.rand(3,3) # two dimensions
np.random.randint(1,100,10) # 10 random int between 1 and 100


In [ ]:
# operations

arr + arr
arr - arr
arr * arr

# scalar

arr + 100
arr * 100
arr - 100

# other

arr**2 # every element squared by two
np.sqrt(arr) # sqr root of every element
np.exp(arr)
np.sin(arr)
np.log(arr)

# for more check universal functions numpy array

In [4]:
list = [1,2,3,4]
array = np.array(list)
array


array([1, 2, 3, 4])

In [6]:
print (f'array shape:{array.shape}')

array shape:(4,)


In [7]:
np.reshape(array, (2,2))

array([[1, 2],
       [3, 4]])

In [8]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [28]:
lins = np.linspace(0.3,19,20) # equally spaced

np.reshape(lins,(5,4))

print ('\n',lins)




 [ 0.3         1.28421053  2.26842105  3.25263158  4.23684211  5.22105263
  6.20526316  7.18947368  8.17368421  9.15789474 10.14210526 11.12631579
 12.11052632 13.09473684 14.07894737 15.06315789 16.04736842 17.03157895
 18.01578947 19.        ]


In [35]:
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print (arr2)



[[1 2 3]
 [4 5 6]]


In [34]:
arr3 = np.array([arr2, [[7, 8, 9], [10, 11, 12]]])
print (arr3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [47]:
print (np.zeros((2,2,2,2)))

print (np.shape)



[[[[0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]]]


 [[[0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]]]]
<function shape at 0x110808488>


In [50]:
arr = np.array([[1,2,3,4],[3,4,5,4],[5,6,7,4],[8,9,10,4]])
print (arr)
np.reshape(arr,(2,2,2,2))


[[ 1  2  3  4]
 [ 3  4  5  4]
 [ 5  6  7  4]
 [ 8  9 10  4]]


array([[[[ 1,  2],
         [ 3,  4]],

        [[ 3,  4],
         [ 5,  4]]],


       [[[ 5,  6],
         [ 7,  4]],

        [[ 8,  9],
         [10,  4]]]])

In [70]:
lins = np.linspace(1,10,256)

In [71]:
print(lins)

[ 1.          1.03529412  1.07058824  1.10588235  1.14117647  1.17647059
  1.21176471  1.24705882  1.28235294  1.31764706  1.35294118  1.38823529
  1.42352941  1.45882353  1.49411765  1.52941176  1.56470588  1.6
  1.63529412  1.67058824  1.70588235  1.74117647  1.77647059  1.81176471
  1.84705882  1.88235294  1.91764706  1.95294118  1.98823529  2.02352941
  2.05882353  2.09411765  2.12941176  2.16470588  2.2         2.23529412
  2.27058824  2.30588235  2.34117647  2.37647059  2.41176471  2.44705882
  2.48235294  2.51764706  2.55294118  2.58823529  2.62352941  2.65882353
  2.69411765  2.72941176  2.76470588  2.8         2.83529412  2.87058824
  2.90588235  2.94117647  2.97647059  3.01176471  3.04705882  3.08235294
  3.11764706  3.15294118  3.18823529  3.22352941  3.25882353  3.29411765
  3.32941176  3.36470588  3.4         3.43529412  3.47058824  3.50588235
  3.54117647  3.57647059  3.61176471  3.64705882  3.68235294  3.71764706
  3.75294118  3.78823529  3.82352941  3.85882353  3.894117

In [72]:
print (np.reshape(lins,(2,2,2,2,2,2,2,2))) #8 dimensional array
print ('\n')



[[[[[[[[ 1.          1.03529412]
       [ 1.07058824  1.10588235]]

      [[ 1.14117647  1.17647059]
       [ 1.21176471  1.24705882]]]


     [[[ 1.28235294  1.31764706]
       [ 1.35294118  1.38823529]]

      [[ 1.42352941  1.45882353]
       [ 1.49411765  1.52941176]]]]



    [[[[ 1.56470588  1.6       ]
       [ 1.63529412  1.67058824]]

      [[ 1.70588235  1.74117647]
       [ 1.77647059  1.81176471]]]


     [[[ 1.84705882  1.88235294]
       [ 1.91764706  1.95294118]]

      [[ 1.98823529  2.02352941]
       [ 2.05882353  2.09411765]]]]]




   [[[[[ 2.12941176  2.16470588]
       [ 2.2         2.23529412]]

      [[ 2.27058824  2.30588235]
       [ 2.34117647  2.37647059]]]


     [[[ 2.41176471  2.44705882]
       [ 2.48235294  2.51764706]]

      [[ 2.55294118  2.58823529]
       [ 2.62352941  2.65882353]]]]



    [[[[ 2.69411765  2.72941176]
       [ 2.76470588  2.8       ]]

      [[ 2.83529412  2.87058824]
       [ 2.90588235  2.94117647]]]


     [[[ 2.97647059  3.011

In [73]:
np.repeat([1,2,3,4],4)

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4])

In [74]:

# create a dataframe which we'll play around with stacking# create 
arr = np.array([[1, 2, 3], [4, 5, 6]])

print('arr:\n', arr, '\n')

# lets stack the same array vertically
vstacked = np.vstack([arr, arr])

print('vstacked:\n', vstacked, '\n')

# lets stack the same array horizontally
hstacked = np.hstack([arr, arr])

print('hstacked:\n', hstacked, '\n')

arr:
 [[1 2 3]
 [4 5 6]] 

vstacked:
 [[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]] 

hstacked:
 [[1 2 3 1 2 3]
 [4 5 6 4 5 6]] 



Operations and arithmetic

In [75]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

print('addition:\n', x + y, '\n')
print('subtraction:\n', x - y, '\n')
print('multiplication:\n', x * y, '\n')
print('division:\n', x / y, '\n')
print('power:\n', x ** 2, '\n')

addition:
 [5 7 9] 

subtraction:
 [-3 -3 -3] 

multiplication:
 [ 4 10 18] 

division:
 [0.25 0.4  0.5 ] 

power:
 [1 4 9] 



In [76]:
x.dot(y)


32

In [83]:
arr = np.array([[1,2,3],[[4,5,6]]])
print(arr)
vec = np.array([10,100]).reshape((-1,1))
print ('\n')
print (vec)

print ('\n')
print (vec.T)



[list([1, 2, 3]) list([[4, 5, 6]])]


[[ 10]
 [100]]


[[ 10 100]]


In [84]:
np.random?

In [86]:
np.random.normal(size=10)

array([-0.41431851, -1.04161911, -2.42670703,  0.03877125,  0.50800091,
       -1.99264149, -0.04742887, -0.96728155, -0.80454265, -0.22666356])